{
 "title": "Application - 开箱即用",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "deepflowio-deepflow-datasource" },
   {
    "name": "cluster",
    "query": {}
   },
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "server",
    "query": {}
   },
   { "name": "endpoint", "query": "*" },
   {
    "name": "l7_protocol",
    "query": {}
   },
   { "name": "deepflow_tracing_id", "query": "*" },
   {
    "name": "signal_source",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "使用说明",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "使用说明",
     "type": "text",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# 1. 变量说明\n\n以下变量作用于除`调用链追踪`以外的所有图表：\n- cluster：服务端服务所在的 K8s 集群\n- namespace：服务端服务所在的命名空间\n- server：服务端服务\n- endpoint：端点，HTTP/RPC 类协议支持提取端点，其他协议为空\n- l7_protocol：应用协议，对应 HTTP/DNS/MySQL 等等应用协议\n- signal_source：信号源，目前支持进行区分的三种信号源为 Packet (cBPF)、eBPF、OTel\n  - eBPF：使用 eBPF 采集的函数调用数据，Dashboard 默认查看的是 eBPF 信号源（[对内核版本有要求](https://deepflow.io/docs/zh/ce-install/overview/#运行权限及内核要求)），如果此信号源无数据，可切换到 Packet 查看数据\n  - Packet：使用 AF_PACKET + cBPF 采集的网卡流量数据\n  - OTel：使用 OTEL 协议接收到的分布式追踪数据\n\n以下图表全部基于 DeepFlow 数据构建。\n\n# 2. 端点列表\n\n端点列表可查看`服务端服务 (auto_service_1)`、`端点 (endpoint)`、`应用协议 (l7_protocol)` 对应的`请求速率`、`响应异常`、`响应时延`指标量。表格支持的操作如下：\n- 点击指标量的表头可进行排序，快速过滤出异常比例高或响应时延大的服务端点\n- 点击表格某一行，将打开一个新页面，展示点击行对应的`服务端服务 + 端点 + 应用协议`的端点详情\n\n指标量的详细说明，请参考 [DeepFlow 官网上的指标量说明](https://deepflow.io/docs/zh/features/universal-map/metrics-and-operators/#应用性能指标)。\n\n# 3. 端点详情\n\n通过指标折线图、调用日志表格以及分布式追踪火焰图展示端点的详情信息。\n\n## 3.1. 指标折线图\n\n- **请求速率**：查看 `server + endpoint + l7_protcol` 变量对应的请求速率变化趋势，图例由`$服务端服务 $应用协议 $端点`组成。\n- **响应时延**：查看 `server + endpoint + l7_protcol` 变量对应的响应时延变化趋势，其中包含`P90 响应时延`及`P99 响应时延`两个指标量，图例由`$服务端服务 $应用协议 $端点-$指标量名称`组成。\n- **异常比例**：查看 `server + endpoint + l7_protcol` 变量对应的异常比例变化趋势，其中包含`客户端异常比例`及`服务端异常比例`两个指标量，图例由`$服务端服务 $应用协议 $端点-$指标量名称`组成。\n- **超时总数**：查看 `server + endpoint + l7_protcol` 变量对应的超时变化趋势，图例由`$服务端服务 $应用协议 $端点`组成。\n\n## 3.2. 调用列表\n\n查看 `server + endpoint + l7_protcol` 变量对应的调用详情列表，可查看客户端服务、响应码、响应异常描述等等信息。表格支持的操作如下：\n- 点击`响应状态`表头`漏斗 ICON`，支持根据响应状态过滤数据\n- 点击`响应时延`表头，支持按指标量进行排序\n- 点击表格中的某一行，可对当前调用进行追踪，结果可在`调用链追踪`对应的火焰图中查看\n\n## 3.3. 调用链追踪\n\n调用链追踪通过火焰图形式展示，对于火焰图的使用可参考 [DeepFlow 官网调用链追踪的说明](https://deepflow.io/docs/zh/guide/ee-tenant/dashboard/panel/flame/)。"
     }
    }
   ]
  },
  { "title": "端点列表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "端点列表",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d4ee9d24-88e5-e61b-3b75-04632c0c4ba7\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"c8855acb-4e4b-aa65-6d08-06c06f546982\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"80754042-4f53-2f98-d3c3-abdd3c8f204b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"979afd36-4083-d5b9-3613-5ee1bfb6f57e\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"metric\",\"key\":\"request\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"11ec40a4-9b32-81af-201d-aaedce6364f1\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}},{\"type\":\"metric\",\"key\":\"client_error_ratio\",\"func\":\"Max\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6588a489-2cd6-04dc-4169-71bddd40a539\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Max\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"server_error_ratio\",\"func\":\"Max\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"b56abf09-c508-a7b7-bdb7-a2744976c56f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Max\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"timeout\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"2791fc39-ea75-a7e9-7569-ced6faae0355\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"rrt_max\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[\"90\"],\"uuid\":\"0efb5384-eb46-d2ae-b287-f7c96c5630fe\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"90\"]}},{\"type\":\"metric\",\"key\":\"rrt_max\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[\"99\"],\"uuid\":\"3f0d79ea-ce45-6d10-3ec6-e7c960234718\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"99\"]}}],\"where\":[{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$l7_protocol\",\"value\":\"l7_protocol\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f60b0d0f-7a3c-49cd-21b9-b2de67b4e8eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"5054578a-2ff8-5c5f-c22a-2dd63987f40c\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"d0f672e3-c2b0-4013-abce-be95dc1de4e3\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$server\",\"value\":\"server\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"d6a6ab8e-fa60-d897-5119-f93375042677\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$endpoint\",\"value\":\"endpoint\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"b38f08ac-2ae8-9b08-1f85-e99e9f74b54d\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"3b93b04e-47b7-25c3-b904-0393087c303a\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6078b6be-8759-4018-a0bb-e8baaed7f8f2\",\"type\":\"metric\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"14f45d17-ea2b-2b57-65c8-4535191bcf39\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"34e873e9-b6a8-d92c-a287-4921503dfbe9\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3fd198d5-0df9-2044-4aad-28eb8a8e330b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"97895847-de97-b26d-9a4a-8b44c1a36831\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"table\",\"alias\":\"\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "PerSecond(Avg(Request))", "name": "PerSecond(Avg(Request))", "type": 1, "unit": "/s" },
      { "displayName": "Max(Client Error %)", "name": "Max(Client Error %)", "type": 4, "unit": "%" },
      { "displayName": "Max(Server Error %)", "name": "Max(Server Error %)", "type": 4, "unit": "%" },
      { "displayName": "Sum(Timeout)", "name": "Sum(Timeout)", "type": 1, "unit": "" },
      { "displayName": "Percentile(Max Delay,0.9)", "name": "Percentile(Max Delay,0.9)", "type": 3, "unit": "us" },
      { "displayName": "Percentile(Max Delay,0.99)", "name": "Percentile(Max Delay,0.99)", "type": 3, "unit": "us" }
     ],
     "returnTags": [
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_1",
       "role": "server"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "Enum(l7_protocol)"
      },
      {
       "displayName": "Endpoint",
       "isResource": false,
       "name": "endpoint"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_1",
       "role": "server"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "l7_protocol"
      }
     ],
     "sql": "SELECT PerSecond(Avg(`request`)) AS `PerSecond(Avg(Request))`, Max(`client_error_ratio`) AS `Max(Client Error %)`, Max(`server_error_ratio`) AS `Max(Server Error %)`, Sum(`timeout`) AS `Sum(Timeout)`, Percentile(`rrt_max`,0.9) AS `Percentile(Max Delay,0.9)`, Percentile(`rrt_max`,0.99) AS `Percentile(Max Delay,0.99)`, auto_service_1, Enum(l7_protocol), endpoint, auto_service_id_1, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, l7_protocol FROM application_map WHERE exist(`l7_protocol`) AND exist(pod_cluster_id_1) AND exist(pod_ns_id_1) AND exist(auto_service_id_1) AND `endpoint` LIKE('*') AND `signal_source` IN ('3') AND time>=1716185580 AND time<=1716186480 GROUP BY auto_service_1, l7_protocol, endpoint, auto_service_id_1, `server_node_type` LIMIT 1000"
    }
   ]
  },
  { "title": "端点详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "请求速率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"c8855acb-4e4b-aa65-6d08-06c06f546982\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"80754042-4f53-2f98-d3c3-abdd3c8f204b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"979afd36-4083-d5b9-3613-5ee1bfb6f57e\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"metric\",\"key\":\"request\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"11ec40a4-9b32-81af-201d-aaedce6364f1\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}}],\"where\":[{\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f536818b-c94a-707b-ca21-fce1b5daebd0\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$l7_protocol\",\"value\":\"l7_protocol\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f60b0d0f-7a3c-49cd-21b9-b2de67b4e8eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4b920d25-0487-c3e8-486c-048003707c5a\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"6c6a691b-ab9f-57ac-3c18-3276b7594fcd\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$server\",\"value\":\"server\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"bbb8356d-341c-ed53-ef42-c66265fa9f43\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$endpoint\",\"value\":\"endpoint\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4eb413c0-ca8c-afc5-62d9-2a056c68c618\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"170ca950-6ed4-a0c3-0352-7a87c386cb56\",\"type\":\"metric\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"14f45d17-ea2b-2b57-65c8-4535191bcf39\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"34e873e9-b6a8-d92c-a287-4921503dfbe9\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3fd198d5-0df9-2044-4aad-28eb8a8e330b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"97895847-de97-b26d-9a4a-8b44c1a36831\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"10\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1} ${Enum(l7_protocol)} ${endpoint}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "PerSecond(Avg(Request))", "name": "PerSecond(Avg(Request))", "type": 1, "unit": "/s" }
     ],
     "returnTags": [
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_1",
       "role": "server"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "Enum(l7_protocol)"
      },
      {
       "displayName": "Endpoint",
       "isResource": false,
       "name": "endpoint"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_1",
       "role": "server"
      },
      {
       "displayName": "time_value",
       "isResource": false,
       "name": "`time_value`"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "l7_protocol"
      }
     ],
     "sql": "SELECT PerSecond(Avg(`request`)) AS `PerSecond(Avg(Request))`, auto_service_1, Enum(l7_protocol), endpoint, auto_service_id_1, time(time, $__interval) AS `time_value`, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, l7_protocol FROM application_map WHERE `signal_source` IN ('3') AND exist(`l7_protocol`) AND exist(pod_cluster_id_1) AND exist(pod_ns_id_1) AND exist(auto_service_id_1) AND `endpoint` LIKE('*') AND time>=1716185580 AND time<=1716186480 GROUP BY `time_value`, auto_service_1, l7_protocol, endpoint, auto_service_id_1, `server_node_type` SLIMIT 10 LIMIT 1000"
    }
   ]
  },
  {
   "title": "响应时延",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"c8855acb-4e4b-aa65-6d08-06c06f546982\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"80754042-4f53-2f98-d3c3-abdd3c8f204b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"979afd36-4083-d5b9-3613-5ee1bfb6f57e\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"metric\",\"key\":\"rrt_max\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"P90响应时延\",\"params\":[\"90\"],\"uuid\":\"0efb5384-eb46-d2ae-b287-f7c96c5630fe\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"90\"]}},{\"type\":\"metric\",\"key\":\"rrt_max\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"P99响应时延\",\"params\":[\"99\"],\"uuid\":\"3f0d79ea-ce45-6d10-3ec6-e7c960234718\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"99\"]}}],\"where\":[{\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f536818b-c94a-707b-ca21-fce1b5daebd0\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$l7_protocol\",\"value\":\"l7_protocol\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f60b0d0f-7a3c-49cd-21b9-b2de67b4e8eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"32a456dd-1e3e-6d9e-fbbf-1b00ff9d4ce6\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"2273c930-e553-1418-98b0-3ef9861180af\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$server\",\"value\":\"server\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"bbb8356d-341c-ed53-ef42-c66265fa9f43\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$endpoint\",\"value\":\"endpoint\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"d8e0d2c1-4531-7b95-a370-d869f433af38\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"76dd656e-bc7d-af3a-29e0-57bab3a1efa7\",\"type\":\"metric\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"14f45d17-ea2b-2b57-65c8-4535191bcf39\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"34e873e9-b6a8-d92c-a287-4921503dfbe9\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3fd198d5-0df9-2044-4aad-28eb8a8e330b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"97895847-de97-b26d-9a4a-8b44c1a36831\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"10\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1} ${Enum(l7_protocol)} ${endpoint}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "P90响应时延", "name": "P90响应时延", "type": 3, "unit": "us" },
      { "displayName": "P99响应时延", "name": "P99响应时延", "type": 3, "unit": "us" }
     ],
     "returnTags": [
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_1",
       "role": "server"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "Enum(l7_protocol)"
      },
      {
       "displayName": "Endpoint",
       "isResource": false,
       "name": "endpoint"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_1",
       "role": "server"
      },
      {
       "displayName": "time_value",
       "isResource": false,
       "name": "`time_value`"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "l7_protocol"
      }
     ],
     "sql": "SELECT Percentile(`rrt_max`,0.9) AS `P90响应时延`, Percentile(`rrt_max`,0.99) AS `P99响应时延`, auto_service_1, Enum(l7_protocol), endpoint, auto_service_id_1, time(time, $__interval) AS `time_value`, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, l7_protocol FROM application_map WHERE `signal_source` IN ('3') AND exist(`l7_protocol`) AND exist(pod_cluster_id_1) AND exist(pod_ns_id_1) AND exist(auto_service_id_1) AND `endpoint` LIKE('*') AND time>=1716185497 AND time<=1716187297 GROUP BY `time_value`, auto_service_1, l7_protocol, endpoint, auto_service_id_1, `server_node_type` SLIMIT 10 LIMIT 1000"
    }
   ]
  },
  {
   "title": "异常比例",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"c8855acb-4e4b-aa65-6d08-06c06f546982\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"80754042-4f53-2f98-d3c3-abdd3c8f204b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"979afd36-4083-d5b9-3613-5ee1bfb6f57e\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"metric\",\"key\":\"client_error_ratio\",\"func\":\"Max\",\"op\":\"\",\"val\":\"\",\"as\":\"客户端异常\",\"params\":[],\"uuid\":\"6588a489-2cd6-04dc-4169-71bddd40a539\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Max\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"server_error_ratio\",\"func\":\"Max\",\"op\":\"\",\"val\":\"\",\"as\":\"服务端异常\",\"params\":[],\"uuid\":\"b56abf09-c508-a7b7-bdb7-a2744976c56f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Max\",\"params\":[]}}],\"where\":[{\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f536818b-c94a-707b-ca21-fce1b5daebd0\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$l7_protocol\",\"value\":\"l7_protocol\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f60b0d0f-7a3c-49cd-21b9-b2de67b4e8eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"d762e437-2e8c-f8d4-d067-cdbb09440a7a\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"d82208e7-7f64-57fa-cc86-630d42b2daed\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$server\",\"value\":\"server\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"bbb8356d-341c-ed53-ef42-c66265fa9f43\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$endpoint\",\"value\":\"endpoint\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"aa6d01cb-0078-d40c-fffe-f09198d1a637\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d316f110-46df-948a-1b35-6778b87a5f95\",\"type\":\"metric\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"14f45d17-ea2b-2b57-65c8-4535191bcf39\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"34e873e9-b6a8-d92c-a287-4921503dfbe9\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3fd198d5-0df9-2044-4aad-28eb8a8e330b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"97895847-de97-b26d-9a4a-8b44c1a36831\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"10\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1} ${Enum(l7_protocol)} ${endpoint}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "客户端异常", "name": "客户端异常", "type": 4, "unit": "%" },
      { "displayName": "服务端异常", "name": "服务端异常", "type": 4, "unit": "%" }
     ],
     "returnTags": [
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_1",
       "role": "server"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "Enum(l7_protocol)"
      },
      {
       "displayName": "Endpoint",
       "isResource": false,
       "name": "endpoint"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_1",
       "role": "server"
      },
      {
       "displayName": "time_value",
       "isResource": false,
       "name": "`time_value`"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "l7_protocol"
      }
     ],
     "sql": "SELECT Max(`client_error_ratio`) AS `客户端异常`, Max(`server_error_ratio`) AS `服务端异常`, auto_service_1, Enum(l7_protocol), endpoint, auto_service_id_1, time(time, $__interval) AS `time_value`, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, l7_protocol FROM application_map WHERE `signal_source` IN ('3') AND exist(`l7_protocol`) AND exist(pod_cluster_id_1) AND exist(pod_ns_id_1) AND exist(auto_service_id_1) AND `endpoint` LIKE('*') AND time>=1716185497 AND time<=1716187297 GROUP BY `time_value`, auto_service_1, l7_protocol, endpoint, auto_service_id_1, `server_node_type` SLIMIT 10 LIMIT 10000"
    }
   ]
  },
  {
   "title": "超时总量",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"c8855acb-4e4b-aa65-6d08-06c06f546982\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"80754042-4f53-2f98-d3c3-abdd3c8f204b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"979afd36-4083-d5b9-3613-5ee1bfb6f57e\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"metric\",\"key\":\"timeout\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"2791fc39-ea75-a7e9-7569-ced6faae0355\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f536818b-c94a-707b-ca21-fce1b5daebd0\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$l7_protocol\",\"value\":\"l7_protocol\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f60b0d0f-7a3c-49cd-21b9-b2de67b4e8eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"73db475d-1308-2806-0505-257245425a41\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"47e38230-2ac7-9719-d31d-2d3b5d64f1de\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$server\",\"value\":\"server\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"bbb8356d-341c-ed53-ef42-c66265fa9f43\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$endpoint\",\"value\":\"endpoint\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"8195bfde-60c7-21a4-3ca7-fba9541d778d\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3daf96e2-a4d2-fc09-7e70-b49a8400ca2e\",\"type\":\"metric\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"14f45d17-ea2b-2b57-65c8-4535191bcf39\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"34e873e9-b6a8-d92c-a287-4921503dfbe9\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"endpoint\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3fd198d5-0df9-2044-4aad-28eb8a8e330b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"97895847-de97-b26d-9a4a-8b44c1a36831\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"$__interval\",\"slimit\":\"10\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1} ${Enum(l7_protocol)} ${endpoint}\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Sum(Timeout)", "name": "Sum(Timeout)", "type": 1, "unit": "" }
     ],
     "returnTags": [
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_1",
       "role": "server"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "Enum(l7_protocol)"
      },
      {
       "displayName": "Endpoint",
       "isResource": false,
       "name": "endpoint"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_1",
       "role": "server"
      },
      {
       "displayName": "time_value",
       "isResource": false,
       "name": "`time_value`"
      },
      {
       "displayName": "节点类型",
       "isResource": true,
       "name": "`server_node_type`",
       "role": "server"
      },
      {
       "displayName": "图标",
       "isResource": true,
       "name": "`server_icon_id`",
       "role": "server"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "l7_protocol"
      }
     ],
     "sql": "SELECT Sum(`timeout`) AS `Sum(Timeout)`, auto_service_1, Enum(l7_protocol), endpoint, auto_service_id_1, time(time, $__interval) AS `time_value`, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, l7_protocol FROM application_map WHERE `signal_source` IN ('3') AND exist(`l7_protocol`) AND exist(pod_cluster_id_1) AND exist(pod_ns_id_1) AND exist(auto_service_id_1) AND `endpoint` LIKE('*') AND time>=1716185497 AND time<=1716187297 GROUP BY `time_value`, auto_service_1, l7_protocol, endpoint, auto_service_id_1, `server_node_type` SLIMIT 10 LIMIT 10000"
    }
   ]
  },
  {
   "title": "调用列表",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "_comment": "Please DON'T modify this variable selection field.",
     "queryText": "{\"appType\":\"appTracing\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"key\":\"auto_service_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d4ee9d24-88e5-e61b-3b75-04632c0c4ba7\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"from\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"b064e052-eb9b-ae3b-a836-65532a44eb7b\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"b4890c93-7a68-9bd1-6c9a-56a82272c8bf\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"request_type\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"abff4e34-1f29-7e63-536d-34d61b5ca7dd\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"request_domain\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"c5ed5940-d402-c847-6b17-7ddb62c9b759\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"request_resource\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"1c755824-7dcd-74c3-5261-ef73af3416ee\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"102be145-394f-e291-a5e8-7a201bb5e3c3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_code\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"0bc267d0-3817-3fb9-4c98-fc791b773cf3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_exception\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"2e819def-47a8-2483-6d30-17789be635c4\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"metric\",\"key\":\"response_duration\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"b1ad3c0b-d860-1612-82a8-23fc0e0e5b52\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"where\":[{\"key\":\"endpoint\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$endpoint\",\"value\":\"endpoint\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"0256776d-65a9-5134-8ce7-0eb1f35eaa08\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$l7_protocol\",\"value\":\"l7_protocol\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"d944642f-87cd-bc79-b5eb-41cb0e04914a\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"b9ffdaa2-b262-64bc-fae5-4a4b9d181ce1\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"pod_ns_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"3c2a64b6-ad8b-6370-d2d2-19a9d4660b39\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$server\",\"value\":\"server\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"9aaa4d2f-c967-f44e-fabe-019bf796e7fe\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"signal_source\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$signal_source\",\"value\":\"signal_source\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"02945035-da2b-5c78-133e-de37bc81eaef\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Server Process\",\"value\":\"s-p\"},{\"label\":\"Server NIC\",\"value\":\"s\"}],\"as\":\"\",\"params\":[],\"uuid\":\"5ffaa031-bcbf-b62a-edbb-ccbe5409dfff\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"50fff64c-d3b4-4d2e-801a-3e4d5ce59f31\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9732ea75-fc2d-1d6f-2ce8-db3d5f999dfe\",\"type\":\"tag\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"97895847-de97-b26d-9a4a-8b44c1a36831\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"\",\"alias\":\"\",\"showMetrics\":-1,\"tracingId\":null}",
     "returnMetrics": [
      { "displayName": "Response Delay", "name": "Response Delay", "type": 3, "unit": "us" }
     ],
     "returnTags": [
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_0",
       "role": "client"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_1",
       "role": "server"
      },
      {
       "displayName": "Application Protocol",
       "isResource": false,
       "name": "Enum(l7_protocol)"
      },
      {
       "displayName": "Request Type",
       "isResource": false,
       "name": "request_type"
      },
      {
       "displayName": "Request Domain",
       "isResource": false,
       "name": "request_domain"
      },
      {
       "displayName": "Request Resource",
       "isResource": false,
       "name": "request_resource"
      },
      {
       "displayName": "Response Status",
       "isResource": false,
       "name": "Enum(response_status)"
      },
      {
       "displayName": "Response Code",
       "isResource": false,
       "name": "response_code"
      },
      {
       "displayName": "Response Exception",
       "isResource": false,
       "name": "response_exception"
      },
      {
       "displayName": "UID",
       "isResource": false,
       "name": "toString(_id)"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_0",
       "role": "client"
      },
      {
       "displayName": "Instance - K8s Service First",
       "isResource": true,
       "name": "auto_service_id_1",
       "role": "server"
      }
     ],
     "sql": "SELECT `response_duration` AS `Response Delay`, auto_service_0, auto_service_1, Enum(l7_protocol), request_type, request_domain, request_resource, Enum(response_status), response_code, response_exception, toString(_id), auto_service_id_0, auto_service_id_1 FROM l7_flow_log WHERE `endpoint` LIKE('*') AND exist(`l7_protocol`) AND exist(pod_cluster_id_1) AND exist(pod_ns_id_1) AND exist(auto_service_id_1) AND `signal_source` IN ('3') AND `observation_point` IN ('s-p','s') AND time>=1716185497 AND time<=1716187297 LIMIT 1000"
    }
   ]
  },
  {
   "title": "调用链追踪",
   "type": "deepflowio-tracing-panel",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "queryText": "{\"appType\":\"appTracingFlame\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d4ee9d24-88e5-e61b-3b75-04632c0c4ba7\",\"type\":\"metric\"}],\"where\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"bc518d2a-d9fa-a41e-0e2a-82df339b54b3\",\"type\":\"tag\"}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"420cfa6e-9c11-b174-7aa7-9a64b50808ea\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9732ea75-fc2d-1d6f-2ce8-db3d5f999dfe\",\"type\":\"tag\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"97895847-de97-b26d-9a4a-8b44c1a36831\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"slimit\":\"\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":-1,\"tracingId\":{\"label\":\"$deepflow_tracing_id\",\"value\":\"$deepflow_tracing_id\",\"isVariable\":true,\"variableType\":\"textbox\"}}",
     "returnMetrics": [
      { "displayName": "响应时延", "name": "响应时延", "type": 3, "unit": "微秒" }
     ],
     "returnTags": [
      {
       "displayName": "资源-服务优先",
       "isResource": true,
       "name": "auto_service_0",
       "role": "client"
      },
      {
       "displayName": "资源-服务优先",
       "isResource": true,
       "name": "auto_service_1",
       "role": "server"
      },
      {
       "displayName": "应用协议",
       "isResource": false,
       "name": "Enum(l7_protocol)"
      },
      {
       "displayName": "请求类型",
       "isResource": false,
       "name": "request_type"
      },
      {
       "displayName": "请求域名",
       "isResource": false,
       "name": "request_domain"
      },
      {
       "displayName": "请求资源",
       "isResource": false,
       "name": "request_resource"
      },
      {
       "displayName": "响应状态",
       "isResource": false,
       "name": "Enum(response_status)"
      },
      {
       "displayName": "响应码",
       "isResource": false,
       "name": "response_code"
      },
      {
       "displayName": "响应异常",
       "isResource": false,
       "name": "response_exception"
      },
      {
       "displayName": "UID",
       "isResource": false,
       "name": "toString(_id)"
      },
      {
       "displayName": "资源-服务优先",
       "isResource": true,
       "name": "auto_service_id_0",
       "role": "client"
      },
      {
       "displayName": "资源-服务优先",
       "isResource": true,
       "name": "auto_service_id_1",
       "role": "server"
      }
     ],
     "sql": "SELECT `response_duration` AS `响应时延`, auto_service_0, auto_service_1, Enum(l7_protocol), request_type, request_domain, request_resource, Enum(response_status), response_code, response_exception, toString(_id), auto_service_id_0, auto_service_id_1 FROM l7_flow_log WHERE time>=1704439550 AND time<=1704461150 LIMIT 1000"
    }
   ]
  }
 ]
}