{
 "title": "Application - Redis Monitoring - Cloud",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "deepflowio-deepflow-datasource" },
   {
    "name": "chost",
    "label": "Cloud Host",
    "query": {}
   },
   { "name": "ip", "label": "IP", "query": "0.0.0.0/0" },
   {
    "name": "observation_point",
    "label": "Tap Side",
    "query": {}
   },
   { "name": "client_for_Redis_Analysis", "query": "*" },
   { "name": "deepflow_tracing_id", "query": "*" }
  ]
 },
 "panels": [
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"request\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a352df35-1007-c942-c587-c748170530fd\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"aff8f4fc-a103-a81c-40b1-6d324a8ff23d\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"5a6e4cfa-6be2-4eaa-24f8-59bb581e4f23\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"25528255-95d7-1360-8b1f-0ae5ecc7d611\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"1ae892e8-55cc-2e8e-eace-388498e9ed6b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"0a3bf855-6fda-cf52-dc8a-899a990cda21\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"304ffc5d-3655-8156-ec6c-dd949ca10aa8\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8ee333ff-5f3e-111e-5072-261e5d9bf72a\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"client_error_ratio\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}}],\"where\":[{\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ae98ffff-3942-400d-b43b-9dcafacfc556\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"6984dc3c-0c8a-a8e5-d4fb-2811de9ed086\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"641c4123-43f7-7eaa-23ff-5399762daec4\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"87f3dd01-f20e-2fdd-93d0-a952b9713576\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"server_error_ratio\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ae98ffff-3942-400d-b43b-9dcafacfc556\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"6984dc3c-0c8a-a8e5-d4fb-2811de9ed086\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"641c4123-43f7-7eaa-23ff-5399762daec4\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"983914ce-58a1-c9b8-2877-e0e9daeb0e4c\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "Redis Service Topo",
   "type": "deepflowio-topo-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "{\"appType\":\"accessRelationship\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"request\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"request_rate\",\"params\":[],\"uuid\":\"9d4505cc-8274-23f8-22f7-fb2006d0d0b3\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}},{\"type\":\"metric\",\"key\":\"rrt\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"delay_avg\",\"params\":[],\"uuid\":\"513bbd90-971c-2b7a-4908-06f27e944593\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"rrt_max\",\"func\":\"Max\",\"op\":\"\",\"val\":\"\",\"as\":\"delay_max\",\"params\":[],\"uuid\":\"8e5e8400-3f7d-30a2-35ce-669f55824c74\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Max\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"server_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"server_error_sum\",\"params\":[],\"uuid\":\"3d5f8273-052e-ffa4-cbbd-357807bab760\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},{\"type\":\"metric\",\"key\":\"timeout\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"time_out\",\"params\":[],\"uuid\":\"da39d8e3-23c9-aa37-e9ba-bf8684d4d9df\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}}],\"where\":[{\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"eb0143cd-5999-d802-9d67-df5ece4c72f6\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"58f11594-d61b-b6b1-5951-26da37367400\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"77b5e4eb-2a8f-7fa4-0fb0-0f2dae18e94f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"756a1bdb-c70e-6e6f-cfeb-f183bc378008\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"71b8d05e-f108-5be4-e592-7cc66559963e\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"from\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"4ea80059-5d63-1914-b948-e3ef51fc4927\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"c789c720-e6a5-d87f-a929-0b889724ac94\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"b2f6bebe-15ee-14f3-888d-945414181cf0\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"client_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ae98ffff-3942-400d-b43b-9dcafacfc556\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"6984dc3c-0c8a-a8e5-d4fb-2811de9ed086\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":false,\"isIpType\":true},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"641c4123-43f7-7eaa-23ff-5399762daec4\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"1dfe8888-0487-ddb6-541f-a1c38d788162\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"server_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ae98ffff-3942-400d-b43b-9dcafacfc556\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"6984dc3c-0c8a-a8e5-d4fb-2811de9ed086\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"641c4123-43f7-7eaa-23ff-5399762daec4\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"41d67ca5-2602-6bad-3689-bbdeccf88812\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "Network Latency Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"rrt\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"Network Latency\",\"params\":[],\"uuid\":\"36fef3a9-26bf-494c-e074-9b3978ab0f57\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[]}}],\"where\":[{\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"86ead6d6-1d46-1c0a-5c2a-80fe24d697cf\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ec107d92-3c41-f6e0-5d53-6b362ebac6b4\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"6f24766c-39d4-57d4-dfa2-b1181f6a76a9\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"2cae401b-aa90-ae87-c12a-5bf719c3d397\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"50777c26-43a3-1c64-e6c5-eb2a73914d42\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"427b85d8-f869-77b1-f14c-32cf68ca670a\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"2b5d7b5e-f60b-4e82-9fb3-85fe2d52f359\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"1\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"network_map\",\"select\":[{\"type\":\"metric\",\"key\":\"byte_rx\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"Send\",\"params\":[],\"uuid\":\"ca168812-c7a1-41c0-12cf-7e2166b2fb5d\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}}],\"where\":[{\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"98046797-4314-dd6a-fdab-1db7d246e39b\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f04c9c48-43ac-f175-288e-3b2c33cab848\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"7fdfd186-a32e-58e9-3b1e-ec0d6c58515f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"2fe272ca-2ded-11fa-e05c-aa2cbf15c1dd\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"91122c7e-c788-97e0-f559-894b94b2e2ce\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"ac26e4f4-bd7f-9815-ad1e-e27eafd71eba\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"Send\",\"showMetrics\":0,\"tracingId\":null}"
    },
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"network_map\",\"select\":[{\"key\":\"byte_tx\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"Receive\",\"params\":[],\"uuid\":\"d60964fe-e9fb-31d2-2d62-048aca2ba702\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}}],\"where\":[{\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"98046797-4314-dd6a-fdab-1db7d246e39b\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f04c9c48-43ac-f175-288e-3b2c33cab848\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"7fdfd186-a32e-58e9-3b1e-ec0d6c58515f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"2fe272ca-2ded-11fa-e05c-aa2cbf15c1dd\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"region_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"91122c7e-c788-97e0-f559-894b94b2e2ce\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"ac26e4f4-bd7f-9815-ad1e-e27eafd71eba\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"Receive\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"request\",\"func\":\"Avg\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[{\"func\":\"PerSecond\"}],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Avg\",\"params\":[],\"subFuncs\":[{\"func\":\"PerSecond\"}]}}],\"where\":[{\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"6cf2cc02-8295-a7fa-58d8-2d14ec4c929a\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4997090a-952d-fc30-baab-1c14910f8ca8\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"3b402395-c288-8ea5-936c-47486ad2aac5\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"79e2276e-de17-d85f-96e9-c3c466363df9\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6d525586-54f0-762b-3414-6a5dc133b814\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_instance_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a5a2e628-5c62-f040-8e97-65ee09d43c5c\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"protocol\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f8c64fee-be67-83be-9ff1-e014f0797864\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"78cdd46e-d117-bc49-ff5f-d4b1230dacf1\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_instance_1}\",\"showMetrics\":0,\"tracingId\":null}"
      }
     ]
    },
    {
     "title": "Request (by client)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"request\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"request\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"6cf2cc02-8295-a7fa-58d8-2d14ec4c929a\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4997090a-952d-fc30-baab-1c14910f8ca8\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"658171c6-b6f4-9611-386a-49ecc446b77e\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"79e2276e-de17-d85f-96e9-c3c466363df9\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6d525586-54f0-762b-3414-6a5dc133b814\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a5a2e628-5c62-f040-8e97-65ee09d43c5c\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"from\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"protocol\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f8c64fee-be67-83be-9ff1-e014f0797864\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"78cdd46e-d117-bc49-ff5f-d4b1230dacf1\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"10\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_instance_0}\",\"showMetrics\":0,\"tracingId\":null}"
      }
     ]
    }
   ]
  },
  { "title": "Delay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"rrt\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"P90\",\"params\":[\"90\"],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"90\"]}}],\"where\":[{\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ae98ffff-3942-400d-b43b-9dcafacfc556\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"cbe69eb3-ac42-92fd-ab7d-5ff3e5248d80\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"615e7058-d207-3a28-4d93-479eac66a8eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"38fde680-7393-b962-68b3-d109da931afd\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"1\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1} P90\",\"showMetrics\":0,\"tracingId\":null}"
    },
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"rrt\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"P95\",\"params\":[\"95\"],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"95\"]}}],\"where\":[{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"cbe69eb3-ac42-92fd-ab7d-5ff3e5248d80\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"pod_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$redis_service\",\"value\":\"redis_service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"9486053e-bfd8-1cb0-8230-39225d23376a\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"615e7058-d207-3a28-4d93-479eac66a8eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"47c03c4c-b34f-af7d-d8f9-c52a42ab5a3e\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"1\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1} P95\",\"showMetrics\":0,\"tracingId\":null}"
    },
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"rrt\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"P99\",\"params\":[\"99\"],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"99\"]}}],\"where\":[{\"key\":\"pod_service_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$redis_service\",\"value\":\"redis_service\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ae98ffff-3942-400d-b43b-9dcafacfc556\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"pod_cluster_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"cbe69eb3-ac42-92fd-ab7d-5ff3e5248d80\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"615e7058-d207-3a28-4d93-479eac66a8eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"8c782231-bf2c-088b-dbcf-83d5923616ae\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"1\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1} P99\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "Delay (by client)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"rrt\",\"func\":\"Percentile\",\"op\":\"\",\"val\":\"\",\"as\":\"P90\",\"params\":[\"90\"],\"uuid\":\"1ca7fff4-5b4f-3983-d742-b067374660a1\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Percentile\",\"params\":[\"90\"]}}],\"where\":[{\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"eb0143cd-5999-d802-9d67-df5ece4c72f6\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"fb60194a-91c4-3eee-6b6e-9f2edb63db2d\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ab0edc8c-0f22-c791-543d-8f4e327ea43f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"8e7c1f83-9f0b-1d95-6477-e0a21b886e91\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"756a1bdb-c70e-6e6f-cfeb-f183bc378008\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8367d9fd-2126-7f0c-71a8-166f647a1d78\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"from\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"b2f6bebe-15ee-14f3-888d-945414181cf0\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"1\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_instance_0} P90\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Server Error",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"server_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"error\",\"params\":[],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ae98ffff-3942-400d-b43b-9dcafacfc556\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"bc739c4a-597c-a766-4c84-16dd523873fd\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"26e665a4-22a7-f01c-52de-9fd725f5fcff\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"b9a62f15-6f9b-d283-2ec7-cf4ce1fcaca1\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1}\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "Client Error",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"client_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"error\",\"params\":[],\"uuid\":\"0df5ecd3-18dc-d5f9-591c-45e12c7e9ae0\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"where\":[{\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ae98ffff-3942-400d-b43b-9dcafacfc556\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"bc739c4a-597c-a766-4c84-16dd523873fd\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"26e665a4-22a7-f01c-52de-9fd725f5fcff\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"cecbe1d1-6e47-05b9-e3e2-6e51eb820dc2\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5f904476-8c4b-cb70-77dd-4d2cc1705fa5\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"96faa5db-3107-0d84-86f0-5d01e1c017d9\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"8d470d47-055e-cf8f-9e69-301062df19db\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1}\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "Server Error (by client)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"server_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"server_error\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"6cf2cc02-8295-a7fa-58d8-2d14ec4c929a\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4cf72c15-65ea-d22d-907f-f81ce868e3f0\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"87f3b4ff-8928-db85-4161-aeb137b33cba\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f5b5beb3-c7e6-9b2c-04a9-f68ce9cfc5bb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6d525586-54f0-762b-3414-6a5dc133b814\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a5a2e628-5c62-f040-8e97-65ee09d43c5c\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"from\",\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"fromSelect0\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"78cdd46e-d117-bc49-ff5f-d4b1230dacf1\",\"type\":\"metric\",\"sort\":\"desc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"key\":\"server_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"client_error\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"interval\":\"\",\"limit\":\"10\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_instance_0}\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "Client Error (by client)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"client_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"client_error\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"6cf2cc02-8295-a7fa-58d8-2d14ec4c929a\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4cf72c15-65ea-d22d-907f-f81ce868e3f0\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"87f3b4ff-8928-db85-4161-aeb137b33cba\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f5b5beb3-c7e6-9b2c-04a9-f68ce9cfc5bb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6d525586-54f0-762b-3414-6a5dc133b814\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a5a2e628-5c62-f040-8e97-65ee09d43c5c\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"from\",\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"fromSelect0\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"78cdd46e-d117-bc49-ff5f-d4b1230dacf1\",\"type\":\"metric\",\"sort\":\"desc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"key\":\"client_error\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"interval\":\"\",\"limit\":\"10\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_instance_0}\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "Time Out (by client)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_metrics\",\"sources\":\"1m\",\"from\":\"application_map\",\"select\":[{\"key\":\"timeout\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"time_out\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"6cf2cc02-8295-a7fa-58d8-2d14ec4c929a\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4cf72c15-65ea-d22d-907f-f81ce868e3f0\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"87f3b4ff-8928-db85-4161-aeb137b33cba\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f5b5beb3-c7e6-9b2c-04a9-f68ce9cfc5bb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6d525586-54f0-762b-3414-6a5dc133b814\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a5a2e628-5c62-f040-8e97-65ee09d43c5c\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"from\",\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"fromSelect0\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"78cdd46e-d117-bc49-ff5f-d4b1230dacf1\",\"type\":\"metric\",\"sort\":\"desc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"key\":\"timeout\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"client_error\",\"params\":[],\"uuid\":\"70eb1649-ff2b-2909-38a5-294dc3be53df\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"interval\":\"\",\"limit\":\"10\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_instance_0}\",\"showMetrics\":0,\"tracingId\":null}"
    }
   ]
  },
  {
   "title": "Log Analysis (Client: ${client_for_Redis_Analysis})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Log (by Key)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"type\":\"metric\",\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"Count\",\"params\":[],\"uuid\":\"dd7ea9f5-1b9f-75ed-898b-722e66754faf\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}},{\"type\":\"tag\",\"key\":\"request_resource\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"Command - Key\",\"params\":[],\"uuid\":\"d1570082-f045-d2f0-1f67-fa0c3d5b0ffb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"where\":[{\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"331638eb-9d52-196c-40db-933e601ae720\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f3fecabb-0a4d-1a7e-234e-8dfc069381be\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$client_for_Redis_Analysis\",\"value\":\"client_for_Redis_Analysis\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"2c43c930-57ab-bff2-4ed2-6e0cc6ac4ada\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"from\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"4e843825-d6bd-47d3-e471-20ec6eda5d1f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"360407cb-f3f8-25f1-9a6e-ccfa3b2b12cc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"aafccbd7-dfbb-553b-f1f2-fff7ae682009\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"request_resource\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6e8d1249-a1f6-0bef-5f95-000a42b52181\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"fromSelect0\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"ecc7fa7a-c053-30f8-fc56-7b6b35ad72e6\",\"type\":\"metric\",\"sort\":\"desc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]},\"fromSelect\":{\"type\":\"metric\",\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"Count\",\"params\":[],\"uuid\":\"dd7ea9f5-1b9f-75ed-898b-722e66754faf\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}}],\"interval\":\"60\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}"
      }
     ]
    },
    {
     "title": "TOP N Command",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"key\":\"request_type\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d60964fe-e9fb-31d2-2d62-048aca2ba702\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"metric\",\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"7af09110-f5d4-ab07-4490-9817e27ca559\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"98046797-4314-dd6a-fdab-1db7d246e39b\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"7388f0c5-2749-57d3-7873-5fea6a741162\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$client_for_Redis_Analysis\",\"value\":\"client_for_Redis_Analysis\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"72395231-3cb7-92f7-8a0b-85395c41b008\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"from\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"a3c928f4-ec3f-aeb8-4bc7-858291941e3e\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"ee0242ef-19a2-26aa-6834-7210aeab9022\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"2fe272ca-2ded-11fa-e05c-aa2cbf15c1dd\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"request_type\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"91122c7e-c788-97e0-f559-894b94b2e2ce\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"fromSelect0\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"ac26e4f4-bd7f-9815-ad1e-e27eafd71eba\",\"type\":\"metric\",\"sort\":\"desc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"type\":\"metric\",\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"7af09110-f5d4-ab07-4490-9817e27ca559\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"interval\":\"\",\"limit\":\"10\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}"
      }
     ]
    },
    {
     "title": "Request Log (by Service)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d60964fe-e9fb-31d2-2d62-048aca2ba702\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"5428ded0-b575-c40e-f585-026a4338e12b\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false}],\"where\":[{\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"98046797-4314-dd6a-fdab-1db7d246e39b\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"2515b825-8d8a-3761-8cd3-8c374cb9587a\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$observation_point\",\"value\":\"observation_point\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"c85e7a93-3c3b-51f1-0345-2d2d64c9ceec\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"5bb82529-ffe5-5c39-7b0f-3265859ba8d7\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$client_for_Redis_Analysis\",\"value\":\"client_for_Redis_Analysis\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"7e80b3df-3004-0a9c-47dd-001e5e9b88e3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"from\"}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"2fe272ca-2ded-11fa-e05c-aa2cbf15c1dd\",\"type\":\"metric\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"auto_service_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a11d4dc3-8c39-1c9c-b885-a1d3fe03ffcf\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false}],\"orderBy\":[{\"key\":\"fromSelect0\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"ac26e4f4-bd7f-9815-ad1e-e27eafd71eba\",\"type\":\"metric\",\"sort\":\"desc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d60964fe-e9fb-31d2-2d62-048aca2ba702\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},\"cache\":{\"func\":\"Sum\",\"params\":[],\"subFuncs\":[]}}],\"interval\":\"60\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"${auto_service_1}\",\"showMetrics\":0,\"tracingId\":null}"
      }
     ]
    },
    {
     "title": "Distributed Tracing (>=100ms)",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "queryText": "{\"appType\":\"appTracing\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"4b03920f-68bf-84e6-989a-023c0a983546\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"from\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"auto_instance_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"295380d3-c64d-9305-ac84-57c50c39e74a\",\"subFuncs\":[],\"whereOnly\":false,\"sideType\":\"to\",\"isResourceType\":true,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"observation_point\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"Tap Side\",\"params\":[],\"uuid\":\"e520efef-cc99-1bcc-ff98-3e57c520c075\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Enum\",\"params\":[]}},{\"type\":\"tag\",\"key\":\"request_type\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"Command\",\"params\":[],\"uuid\":\"98f579bd-ac4d-8f3e-15a4-4a2d62dcc1d1\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"request_resource\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"Request Key\",\"params\":[],\"uuid\":\"cbb6c14d-6766-3900-519d-f35d303c3b6c\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"Enum\",\"op\":\"\",\"val\":\"\",\"as\":\"Status\",\"params\":[],\"uuid\":\"5578a571-0b67-b538-27e4-daae4f01259f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"start_time\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"Start Time\",\"params\":[],\"uuid\":\"beaaf242-d180-dcd2-e952-6eca4e5f62a3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"metric\",\"key\":\"response_duration\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"cc73cdd5-32cf-31c2-b70f-b7af1d03f6eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"where\":[{\"type\":\"tag\",\"key\":\"capture_nic_type\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"eBPF\",\"value\":7},{\"label\":\"OTel\",\"value\":8}],\"as\":\"\",\"params\":[],\"uuid\":\"1e9bce7f-5590-cc71-65ad-c779e3127d60\"},{\"type\":\"tag\",\"key\":\"chost_1\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$chost\",\"value\":\"chost\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"b79356a7-5ba7-12d0-6c6c-f4fca2bc307b\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"ip_1\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$ip\",\"value\":\"ip\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"3cce1372-7eae-7c8c-a380-eb179ec65bf6\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":true,\"sideType\":\"to\"},{\"type\":\"tag\",\"key\":\"auto_instance_0\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$client_for_Redis_Analysis\",\"value\":\"client_for_Redis_Analysis\",\"isVariable\":true,\"variableType\":\"textbox\"}],\"as\":\"\",\"params\":[],\"uuid\":\"1a688fcf-35a6-0b46-13ae-86f1d1f339e7\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":true,\"isIpType\":false,\"sideType\":\"from\"},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"Redis\",\"value\":80}],\"as\":\"\",\"params\":[],\"uuid\":\"0302142d-913b-5227-21f5-f0b6e5d6cb7c\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"fromSelectcc73cdd5-32cf-31c2-b70f-b7af1d03f6eb\",\"func\":\"\",\"op\":\">=\",\"val\":\"100000\",\"as\":\"\",\"params\":[],\"uuid\":\"da18d4b6-9bc6-4019-e684-08ea89d3fcdc\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"type\":\"metric\",\"key\":\"response_duration\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"cc73cdd5-32cf-31c2-b70f-b7af1d03f6eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}}],\"groupBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d04b2ee1-c8a2-6348-cb7e-59f179cc4011\",\"type\":\"tag\"}],\"orderBy\":[{\"key\":\"fromSelectcc73cdd5-32cf-31c2-b70f-b7af1d03f6eb\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"477e97ad-c61c-46ed-c321-f94c72e0fd7e\",\"type\":\"metric\",\"sort\":\"desc\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"fromSelect\":{\"type\":\"metric\",\"key\":\"response_duration\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"cc73cdd5-32cf-31c2-b70f-b7af1d03f6eb\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}}],\"interval\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":null}"
      }
     ]
    },
    {
     "type": "deepflowio-tracing-panel",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
     "targets": [
      {
       "queryText": "{\"appType\":\"appTracingFlame\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"187e7913-b779-5f0a-7c91-ac92e618e76c\",\"type\":\"metric\"}],\"where\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"777737e0-25f9-2e22-9430-82e29583a95b\",\"type\":\"tag\"}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"e95ab83a-a3a1-9a4f-aaf3-574e52db07d9\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9fc585e0-434d-7f77-d293-954a62804138\",\"type\":\"tag\"}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"05646e38-adc6-5802-0493-88ca5dbf6b36\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"100\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\",\"showMetrics\":0,\"tracingId\":{\"label\":\"$deepflow_tracing_id\",\"value\":\"$deepflow_tracing_id\",\"isVariable\":true,\"variableType\":\"textbox\"}}"
      }
     ]
    }
   ]
  }
 ]
}