{
 "title": "DeepFlow Resource",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "mysql" },
   {
    "name": "Domain",
    "label": "Domain Name",
    "query": "select name from deepflow.domain;"
   }
  ]
 },
 "panels": [
  {
   "title": "Domain List",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "deepflow",
     "rawSql": "SELECT name, lcuuid AS uuid FROM deepflow.domain WHERE name='$Domain';"
    }
   ]
  },
  {
   "title": "AZ List",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "deepflow",
     "rawSql": "SELECT name, lcuuid AS uuid, domain FROM deepflow.az WHERE domain=(SELECT lcuuid FROM deepflow.domain WHERE name='$Domain');"
    }
   ]
  },
  {
   "title": "VPC List",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "deepflow",
     "rawSql": "SELECT name, lcuuid AS uuid, domain, az FROM deepflow.epc WHERE domain=(SELECT lcuuid FROM deepflow.domain WHERE name='$Domain');"
    }
   ]
  },
  {
   "title": "Subnet List",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "dataset": "deepflow",
     "rawSql": "SELECT name, lcuuid AS uuid, domain, az FROM deepflow.vl2 WHERE domain=(SELECT lcuuid FROM deepflow.domain WHERE name='$Domain');"
    }
   ]
  },
  {
   "title": "Host List",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "deepflow",
     "rawSql": "SELECT name, lcuuid AS uuid, domain, az, ip FROM deepflow.host_device WHERE domain=(SELECT lcuuid FROM deepflow.domain WHERE name='$Domain');"
    }
   ]
  },
  {
   "title": "CHost List",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "dataset": "deepflow",
     "rawSql": "SELECT name, lcuuid AS uuid, domain, az, launch_server AS host_ip FROM deepflow.vm WHERE domain=(SELECT lcuuid FROM deepflow.domain WHERE name='$Domain');"
    }
   ]
  }
 ]
}