{
 "title": "DeepFlow Server - Controller",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "SELECT tag_values[indexOf(tag_names, 'host')]  from ext_metrics.telegraf_deepflow_server_controller_cloud_api_count"
   },
   {
    "name": "platform",
    "query": "SELECT tag_values[indexOf(tag_names, 'platform')]  from ext_metrics.telegraf_deepflow_server_controller_cloud_api_count"
   },
   {
    "name": "domain_name",
    "query": "SELECT tag_values[indexOf(tag_names, 'domain_name')]  from ext_metrics.telegraf_deepflow_server_controller_cloud_api_count"
   }
  ]
 },
 "panels": [
  {
   "title": "云平台API返回的资源个数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"ext_metrics\",\"sources\":\"\",\"from\":\"telegraf_deepflow_server_controller_cloud_api_count\",\"select\":[{\"key\":\"metrics.value\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"7eb800fc-62de-1757-80cf-b5695f654f66\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}},{\"type\":\"tag\",\"key\":\"tag.type\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"548ee06e-c7c0-31d0-b5df-f035732ee92d\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"e9c9df32-e682-dc8f-af94-a1831137aae2\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.platform\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$platform\",\"value\":\"platform\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"439bc622-feaf-df82-b2f8-10ea425a3134\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.domain_name\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$domain_name\",\"value\":\"domain_name\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"f247d1d1-f78e-0e65-a10e-7b0f51fa2bc7\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"3951408d-697b-43d0-9e57-e54aa957e8db\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.type\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"c8ed9b30-ec07-749d-00a9-a2e9d68959e7\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"0d9d3220-d4f8-c1e1-dcbe-374eff5bcf9c\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"0ecdfd7d-61b1-3c06-9a67-e12ab1cf02a3\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\"}"
    }
   ]
  },
  {
   "title": "云平台API调用的耗时",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"ext_metrics\",\"sources\":\"\",\"from\":\"telegraf_deepflow_server_controller_cloud_api_cost\",\"select\":[{\"key\":\"metrics.mean\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f0938fdc-d83a-d780-e9ab-df9b6a3dcbf5\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ca4411bd-5b3e-a2a1-da46-80ad68dd5774\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.platform\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$platform\",\"value\":\"platform\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"1e179ea7-c074-2173-14a2-e5e262c3cc68\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.domain_name\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$domain_name\",\"value\":\"domain_name\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"40d5a919-6f26-c584-6b7e-92797d33173f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"28c8d614-a7b2-f3c4-4a8f-34d22f9029fe\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.type\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"c7d0207b-6c26-2662-1a61-1e8215162844\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"7bd878a5-ef9f-0234-b0d7-80d5241f251f\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\"}"
    }
   ]
  },
  {
   "title": "云平台API调用的次数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"ext_metrics\",\"sources\":\"\",\"from\":\"telegraf_deepflow_server_controller_cloud_api_cost\",\"select\":[{\"key\":\"metrics.count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f0938fdc-d83a-d780-e9ab-df9b6a3dcbf5\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ca4411bd-5b3e-a2a1-da46-80ad68dd5774\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.platform\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$platform\",\"value\":\"platform\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"1e179ea7-c074-2173-14a2-e5e262c3cc68\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.domain_name\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$domain_name\",\"value\":\"domain_name\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"40d5a919-6f26-c584-6b7e-92797d33173f\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"28c8d614-a7b2-f3c4-4a8f-34d22f9029fe\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.type\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"c7d0207b-6c26-2662-1a61-1e8215162844\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"7bd878a5-ef9f-0234-b0d7-80d5241f251f\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\"}"
    }
   ]
  },
  {
   "title": "Server-cloud API返回的资源个数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"ext_metrics\",\"sources\":\"\",\"from\":\"telegraf_deepflow_server_controller_cloud_info_count\",\"select\":[{\"key\":\"metrics.value\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"f0938fdc-d83a-d780-e9ab-df9b6a3dcbf5\",\"type\":\"metric\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false,\"cache\":{\"func\":\"Sum\",\"params\":[]}}],\"where\":[{\"key\":\"tag.host\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$host\",\"value\":\"host\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ca4411bd-5b3e-a2a1-da46-80ad68dd5774\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.platform\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$platform\",\"value\":\"platform\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"e1b56ef5-cf0e-a040-9696-564dd1e892e3\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false},{\"type\":\"tag\",\"key\":\"tag.domain_name\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$domain_name\",\"value\":\"domain_name\",\"isVariable\":true,\"variableType\":\"query\"}],\"as\":\"\",\"params\":[],\"uuid\":\"bdb45ce7-504a-8dd1-bb9f-4a2ee04f4cc9\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"having\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"28c8d614-a7b2-f3c4-4a8f-34d22f9029fe\",\"type\":\"metric\"}],\"groupBy\":[{\"key\":\"tag.type\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"c7d0207b-6c26-2662-1a61-1e8215162844\",\"type\":\"tag\",\"subFuncs\":[],\"whereOnly\":false,\"isResourceType\":false,\"isIpType\":false}],\"orderBy\":[{\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"7bd878a5-ef9f-0234-b0d7-80d5241f251f\",\"type\":\"metric\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"10000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\"}"
    }
   ]
  }
 ]
}